### ISSUE TITLE
_WD_HighlightElements() refactoring is needed

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#118]
I will do this in future
currently this is just a reminder, I will propose new PR soon

**Comment by mlipok** [comment]
```

Func _WD_HighlightElements($sSession, $aElements, $iMethod = Default)
	Local $iHighlightedElements = 0

	If $iMethod = Default Then $iMethod = 1

	For $i = 0 To UBound($aElements) - 1
		$iHighlightedElements += (_WD_HighlightElement($sSession, $aElements[$i], $iMethod) = True ? 1 : 0)
	Next
	Return ($iHighlightedElements > 0 ? SetError(0, $iHighlightedElements, True) : SetError($_WD_ERROR_GeneralError, 0, False))
EndFunc   ;==>_WD_HighlightElements

```

It's hard to maintain - I had to go over the topic several times to find out what it was about.

There is one issue.
If there are provided 10 elements to highlight and error ocurs on 5th element then procesing should be stoped with error, but it will process to the end, and finallly report success.

I will do some fix for this.

**Comment by Danp2** [comment]
Rewritten in #172
