### ISSUE TITLE
_WD_ElementSelectAction() refactoriong needed

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#119]
`If $iErr = $_WD_ERROR_Success And $sNodeName = 'select' Then`

I will do this in a future.

**Comment by Danp2** [comment]
I don't understand what you intend to change here. Please explain.

**Comment by mlipok** [comment]
> I will do this in a future.

currently this is just a reminder

**Comment by Danp2** [comment]
I'm trying to understand why it needs refactoring. Is there an issue with the line of code you posted above? What's wrong with the function's current code?

**Comment by mlipok** [comment]
currently there is:

```
$sNodeName = _WD_ElementAction($sSession, $sSelectElement, 'property', 'nodeName')
	Local $iErr = @error

	If $iErr = $_WD_ERROR_Success And $sNodeName = 'select' Then
........
........
........
........
	Else
		$iErr = $_WD_ERROR_InvalidArgue
	EndIf

```

In this way you are getting only one kind of @error .... $iErr = $_WD_ERROR_InvalidArgue

I think this should works in this way:

```
	Local $iErr
	$sNodeName = _WD_ElementAction($sSession, $sSelectElement, 'property', 'nodeName')
	If @error Then
		$iErr = @error
	ElseIf $sNodeName <> 'select' Then
		$iErr = $_WD_ERROR_InvalidArgue
	Else
		..........
	EndIf

```

**Comment by Danp2** [comment]
Ok. It would have been helpful if you had included some additional details when you original opened the issue. That way we can understand what you are intending to change and can comment if needed. 😄

**Comment by mlipok** [comment]
All is done in https://github.com/Danp2/WebDriver/pull/165
