### ISSUE TITLE
_WD_ElementActionEx() refactoring needed

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#120]
$sAction
`; Default "hover" action`

I will do this in future

**Comment by Danp2** [comment]
Please elaborate on the proposed changes. The above doesn't really explain the issue.

**Comment by mlipok** [comment]
currently this is just a reminder, I will propose new PR soon

**Comment by mlipok** [comment]
```
			; Build dynamic action string
			$sAction = _
					'{' & _
					'	"actions":['
			If $sPreAction Then $sAction &= _
					'		' & $sPreAction
			; Default "hover" action
			$sAction &= _
					'		{' & _
					'			"id":"hover",' & _
					'			"type":"pointer",' & _
					'			"parameters":{"pointerType":"mouse"},' & _
					'			"actions":[' & _
					'				{' & _
					'					"duration":100,' & _
					'					"x":' & $iXOffset & ',' & _
					'					"y":' & $iYOffset & ',' & _
					'					"type":"pointerMove",' & _
					' 					"origin":{' & _
					' 						"ELEMENT":"' & $sElement & '",' & _
					' 						"' & $_WD_ELEMENT_ID & '":"' & $sElement & '"' & _
					' 					}' & _
					'				}'
			If $sPostHoverAction Then $sAction &= _
					'				' & $sPostHoverAction
			; Close mouse actions
			$sAction &= _
					"			]" & _
					"		}"
			If $sPostAction Then $sAction &= _
					$sPostAction
			; Close main action
			$sAction &= _
					"	]" & _
					"}"

```

In the End I plan to change them to single string, and then:
`StringFormat($sAction, $iXOffset, $iYOffset, .....)`

**Comment by Danp2** [comment]
Sorry, but I don't understand. Please explain how this is an improvement over the current implementation.

**Comment by mlipok** [comment]
please do not feel offened

1. sorry but current code for this JSON part, is ugly to read and dificult to understand 
2. I want to put this entire JSON to internal function and get result from them as once pre-difined string to Static variable
3. Static variable will be changed with StringFormat() in one single line to fullfill parameters

Benefits:
Easier to manage code
Faster operation / processing

**Comment by Danp2** [comment]
No offense taken. Not sure that I would agree that your version is more readable / easier to maintain. I guess beauty is in the eye of the beholder. 😉 

Moving the functionality to a separate function only makes sense to me if this function will be called by more than one routine. But I'm happy to review your submission for possible inclusion to the UDF library.

**Comment by mlipok** [comment]
> No offense taken. Not sure that I would agree that your version is more readable / easier to maintain.

Currently you see only an conceptual scratch.
To see the broader spectrum you have to wait for my sumbission.
Be patient ;)

**Comment by Danp2** [comment]
@mlipok 

>  Not sure that I would agree that your version is more readable / easier to maintain.

I still stand by this statement, and I'm having issues with some of the changes in #130. Please address the following questions --

- How does moving the code to a separate function (__WD_ElementActionExJsonBuilder) improve the balance between simplicity, readability, and maintainability?

- How does adding in a bunch of formatting (spaces, CRs, etc) improve these things (simplicity, readability, and maintainability)?

P.S. The JSON UDF already includes some functionality for "pretty" formatting

**Comment by mlipok** [comment]
> The JSON UDF already includes some functionality for "pretty" formatting
> 
> Edit - Here's an example --

The intention was not to pretty format the JSON String on demand (delinearization), but to have the JSON string formatted in the code (delinearized all the time), to it delinearized when you create it. Because this way is easier to understand and manage the script.

In other words, your example contains a linearized JSON string in the AutoIt script code.
I say that in script JSON string should not be linear.
The JSON string linearization should occur just before passing it to WebDriver.

**Comment by Danp2** [comment]
I can't understand how you think this --
```autoit
Func __WD_JsonButtonAction($iButton, $sAction)
	Return _
			',{' & @CR & _
			'	"button": ' & $iButton & @CR & _
			'	,"type": "' & $sAction & '"' & @CR & _
			'}'
EndFunc   ;==>__WD_JsonButtonAction
```
is easier to read *and* maintain than this --
```autoit
Func __WD_JsonButtonAction($iButton, $sAction)
	Return ',{"button": ' & $iButton & ', "type": "' & $sAction & '"}'
EndFunc   ;==>__WD_JsonButtonAction
```

Perhaps if you had written it like the following, then I could possibly see your point --

```autoit
Func __WD_JsonButtonAction($iButton, $sAction)
	Return _
		',{' & _
		'"button": ' & $iButton & _
		',"type": "' & $sAction & '"' _
		'}'
EndFunc   ;==>__WD_JsonButtonAction
```

IMO, Adding the extra formatting (tabs, spaces, CRs, etc) does nothing but make the script more difficult to maintain. In the end you remove the CR/LFs anyway, so why include them in the first place unless it's for pretty printed output?

**Comment by mlipok** [comment]
> I can't understand how you think this --
> 
> ```autoit
> Func __WD_JsonButtonAction($iButton, $sAction)
> 	Return _
> 			',{' & @CR & _
> 			'	"button": ' & $iButton & @CR & _
> 			'	,"type": "' & $sAction & '"' & @CR & _
> 			'}'
> EndFunc   ;==>__WD_JsonButtonAction
> ```
> 
> is easier to read _and_ maintain

This is normal intendation.
You can check it in Notepad++.
This is normal not only for JSON but also XML, SQL 

For example:
![image](https://user-images.githubusercontent.com/11089482/150433854-6cccde91-2bf8-4877-a90d-33e9896c84d8.png)

**Comment by mlipok** [comment]
> Adding the extra formatting (tabs, spaces, CRs, etc) does nothing but make the script more difficult to maintain. In the end you remove the CR/LFs anyway, so why include them in the first place unless it's for pretty printed output?

I can agree that the Spaces and CRs can be removed.
But I would stay with Tabs then it will look like:

```AutoIt
	Local $sAction = _
			'{' & _
			'	"actions":[' & _ ;Openmainaction
			$sPreAction & _
			'		{' & _ ;Startofdefault"hover"action
			'			"id":"hover"' & _
			'			,"type":"pointer"' & _
			'			,"parameters":{"pointerType":"mouse"}' & _
			'			,"actions":[' & _ ;Openmouseactions
			'				{' & _
			'					"type":"pointerMove"' & _
			'					,"duration":100' & _
			'					,"x":' & $iXOffset & _
			'					,"y":' & $iYOffset & _
			'					,"origin":{' & _
			'						"ELEMENT":"' & $sElement & '"' & _
			'						,"' & $_WD_ELEMENT_ID & '":"' & $sElement & '"' & _
			'					}' & _
			'				}' & _
			$sPostHoverAction & _
			'			]' & _ ;Closemouseactions
			'		}' & _ ;Endofdefault'hover'action
			$sPostAction & _
			'	]' & _ ;Closemainaction
			'}'

```

**Comment by mlipok** [comment]
btw. wait a moment I will offer one more commit then you will se it will be usefull.

**Comment by mlipok** [comment]
take a look again at:
https://github.com/Danp2/WebDriver/pull/130

especially at:
https://github.com/Danp2/WebDriver/pull/130/commits/bef6155353d1f5994a7f35f8e4943ace58531836

**Comment by mlipok** [comment]
> and this part:
> 
> ```autoit
> Local Static $sJSONTemplate = __WD_ElementActionExJsonTemplate()
> $sAction = StringFormat($sJSONTemplate, $sPreAction, $iXOffset, $iYOffset, $sElement, $sElement, $sPostHoverAction, $sPostAction)
> ```

Now we have `$sJSONTemplate` stored in some kind of Storage/Container which is JSON formated string I mean delinearized/tidied in AutoIt Script.
It is called once.

`StringFormat()` does the job fast.

**Comment by mlipok** [comment]
Can we close this ?
