### ISSUE TITLE
_WD_FindElement - cmd processing

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#125]
In `_WD_FindElement` in case when `$sStartNodeID = Default`  >> `$sStartNodeID = ""`

```
		$sBaseCmd = ($bShadowRoot) ? "/shadow/" : "/element/"
		$sBaseCmd &= $sStartNodeID
		.........
		$sCmd = '/element' & (($bMultiple) ? 's' : '')
		.........
		__WD_Post($_WD_BASE_URL & ":" & $_WD_PORT & "/session/" & $sSession & $sBaseCmd & $sCmd, ........
```
can occurs such scenario where `$sBaseCmd & $sCmd` will be `/shadow//element` or `/element//element`

Is this correct that `//` follow each other?
If this is an real issue and should be fixed, then I can propose fix for this.

**Comment by Danp2** [comment]
Not sure that I understand as that section of code should never run when `$sStartNodeID = Default`. Are you saying that the line `If $sStartNodeID Then` won't function correctly in this instance?

There could definitely be some additional error checking to ensure $sStartNodeID is the correct data type.

**Comment by mlipok** [comment]
When `$sStartNodeID = Default` >>> `$sStartNodeID = ""`
In such case this part is not processed
```
	If $sStartNodeID Then
		$sBaseCmd = ($bShadowRoot) ? "/shadow/" : "/element/"
		$sBaseCmd &= $sStartNodeID

		; Make sure using a relative selector if using xpath strategy
		If $sStrategy = $_WD_LOCATOR_ByXPath And StringLeft($sSelector, 1) <> '.' Then
			$iErr = $_WD_ERROR_InvalidExpression
			$sResponse = "Selector must be relative when supplying a starting element"
		EndIf
	EndIf
```

but i such case the next part is still processed:
```
	If $iErr = $_WD_ERROR_Success Then
		$sCmd = '/element' & (($bMultiple) ? 's' : '')
		$sSelector = __WD_EscapeString($sSelector)

		$sResponse = __WD_Post($_WD_BASE_URL & ":" & $_WD_PORT & "/session/" & $sSession & $sBaseCmd & $sCmd, '{"using":"' & $sStrategy & '","value":"' & $sSelector & '"}')
		$iErr = @error
	EndIf
```

so for examle: `$sBaseCmd & $sCmd` will not contain `$sBaseCmd = ($bShadowRoot) ? "/shadow/" : "/element/"` is this correct ?

**Comment by Danp2** [comment]
That's correct, which is by design. This single function covers six different commands as defined in the W3C specs.

**Comment by mlipok** [comment]
ah so this my fault,
Must read more W3C specs 
;)
