### ISSUE TITLE
_WD_UpdateDriver: Maintain $bForce value when Null

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#141]
This line --

https://github.com/Danp2/WebDriver/blob/3057014125c81c3f52e9a23451aa4b1efd2730e9/wd_helper.au3#L1290

changes the value of $bForce, essentially forcing an update even if the calling routine set $bForce = Null, indicating that the function should check for an update without actually performing the update.

This should be fixed so that the Null value is maintained / honored.

**Comment by Danp2** [comment]
I think there is still an issue in this line --

`				If IsKeyword($bForce) = $KEYWORD_NULL And $bUpdateAvail Then`

See my latest commit for proposed changes.

**Comment by mlipok** [comment]
See my latest comment to the commit ;)

**Comment by Danp2** [comment]
Good idea. Should be correct now. ;-)

**Comment by mlipok** [comment]
I think that if someone rase an issue and somebody else reference PR, then almost all further talks should be taken in the PR 
;)

**Comment by Danp2** [comment]
Not sure that I agree. As we discussed the other day, I often find it difficult to follow the "conversations" in PRs. Sometimes it's difficult to catch everything that has been said. We may ultimately decide that your idea is best, but for now I suggest that we continue to try different things until we settle on a "standard". 😄

**Comment by Danp2** [comment]
Here's an example of what I'm having difficulty with. I got the attached email earlier today (it's a .eml file renamed so that I could attach it). When I click the "View it on Github" link, it takes me to https://github.com/Danp2/WebDriver/pull/139#discussion_r791030590.

I can't find the comment "Resolved ?" anywhere on this PR.

😠 

[[Danp2_WebDriver] added _WD_UpdateDriver to demo script (PR #139).txt](https://github.com/Danp2/WebDriver/files/7929432/Danp2_WebDriver.added._WD_UpdateDriver.to.demo.script.PR.139.txt)
-
