### ISSUE TITLE
why DemoActions() uses _WD_Action() ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#145]
After checking it looks like more adequte will be using `_WD_ElementActionEx` .
What you think about ?

**Comment by Danp2** [comment]
> _WD_Element() 

This function doesn't exist. Did you mean _WD_Action?

> _WD_ElementActionEx 

You could add more examples that use _WD_ElementActionEx, but I wouldn't replace the current one. Remember that wd_demo was designed to demonstrate the basic Webdriver functionality, so it makes sense to me to use _WD_Action here. There may be an opportunity to use _WD_JsonAction as well, but I haven't looked into that.

**Comment by mlipok** [comment]
> This function doesn't exist. Did you mean _WD_Action?

Yes, fixed, thanks.
