### ISSUE TITLE
DemoAlerts 'sendtext' issue on Chrome/MSEdge

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#151]
using `wd_demo.au3` in `DemoAlerts()` on `Chrome` and `MSEdge` this part
```AutoIt
	; Set value of text field
	_WD_Alert($sSession, 'sendtext', 'new text')

```

dosen't work.
Any idea why ?

**Comment by mlipok** [comment]
Is this related to:
https://github.com/Danp2/WebDriver/pull/150
?

**Comment by Danp2** [comment]
IDK. It's supposed to be working according to https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md

**Comment by Danp2** [comment]
> is this it:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1120

Looks like that's the one. This proves that it's working as designed --
```autoit
#include "wd_core.au3"
#include "wd_capabilities.au3"

Global $sDesiredCapabilities = SetupChrome()
_WD_Startup()

$sSession = _WD_CreateSession($sDesiredCapabilities)
_WD_Navigate($sSession, "https://demoqa.com/alerts")
$sButton = _WD_FindElement($sSession, $_WD_LOCATOR_ByXPath, "//button[@id='promtButton']")
_WD_ElementAction($sSession, $sButton, 'click')

_WD_Alert($sSession, 'sendtext', 'new text')
Sleep(2000)
_WD_Alert($sSession, 'accept')

Exit

Func SetupChrome()
	_WD_Option('Driver', 'chromedriver.exe')
	_WD_Option('Port', 9515)
	_WD_Option('DriverParams', '--verbose --log-path="' & @ScriptDir & '\chrome.log"')

;~ 	Local $sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"w3c": true, "excludeSwitches": [ "enable-automation"]}}}}'
	_WD_CapabilitiesStartup()
	_WD_CapabilitiesAdd('alwaysMatch', 'chrome')
	_WD_CapabilitiesAdd('w3c', True)
	_WD_CapabilitiesAdd('excludeSwitches', 'enable-automation')
	_WD_CapabilitiesDump(@ScriptLineNumber) ; dump current Capabilities setting to console - only for testing in this demo
	Local $sDesiredCapabilities = _WD_CapabilitiesGet()
	Return $sDesiredCapabilities
EndFunc   ;==>SetupChrome
```

**Comment by mlipok** [comment]
hmmm..
It is sets internaly but is not showed in Alert window.
So this is somehow ChromeDriver or even Chrom issue.

**Comment by Danp2** [comment]
>  So this is somehow ChromeDriver or even Chrom issue.

@mlipok From comment #11 in the prior posted link --

> Due to implementation details of Chrome, it's not possible for Chrome to display the sent text in the prompt dialog. However, the text is recorded and will be returned when the prompt is accepted.

Therefore, it's "by design" and not something they intend to change / fix.
