### ISSUE TITLE
$aDemoSuite new Col for Paramters

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#155]
We should look for a better way to implement this that doesn't involve hardcoding function names. I think we could make this data driven by adding a column to $aDemoSuite. Also, it would make more sense to me to pass the browser name instead of the control ID. This would prevent the need from having code like `$aBrowsers[_GUICtrlComboBox_GetCurSel($idBrowsers)][0]` in multiple routines.

_Originally posted by @Danp2 in https://github.com/Danp2/WebDriver/pull/154#r792939612_

**Comment by Danp2** [comment]
Closed in #157
