### ISSUE TITLE
_WD_JsonAction expansion?

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#164]
Should _WD_JsonAction be expanded to support additional actions (ie: pointerMove)? This would require adding additional parameters, which could make the function more difficult to use.

**Comment by Sven-Seyfert** [comment]
Hi Dan,

there are already four parameters for the function. I know two of them are optional, but why not introduce another function instead of extend _WD_JsonAction()? Personally I prefer small functions in general, especially when it cames to changes within a function => it's just more easy to handle this.

Best regards
Sven

**Comment by Danp2** [comment]
Hi Sven,

Appreciate the feedback. I'm fine with multiple functions as long as they make sense from a naming & functionality standpoint. Based on your input, there are a few ways to handle this --

- Eliminate _WD_JsonAction and split the current functionality across multiple functions, ie: _WD_JsonActionMouse, _WD_JsonActionKey, etc
- Expand the existing _WD_JsonAction so that it contains all JSON action coding. Then write wrapper functions (could be the same function names as above) to provide simpler interfaces for the script writer.

Other comments or suggestions?

Dan

**Comment by Sven-Seyfert** [comment]
I would go with the first suggested variant (multiple functions). Because when you expand the current function and wrap functions to provide a simpler interface, it would look like the following.

``` autoit
; I assume the "pointerMove" would need two additional parameters in this example
Func _WD_JsonAction($sAction, $iValue, $sType = "", $sKey = "", $sPointerMoveVarOne = "", $sPointerMoveVarTwo = "")
	Local $sJSON = ''
	Switch $sAction
		Case 'mouse'
			$sJSON = _
					'{' & _
					'	"button":' & $iValue & _
					'	,"type":"' & $sType & '"' & _
					'}'
		Case 'pause'
			$sJSON = _
					'{' & _
					'	"type":"pause"' & _
					'	,"duration":' & $iValue & _
					'}'

		Case 'key'
			$sJSON = _
					'{' & _
					'	"type":"key"' & _
					'	,"id":"keyboard_' & $iValue & '"' & _
					'	,"actions":[' & _
					'		{' & _
					'			"type":"' & $sType & '"' & _
					'			,"value":"' & $sKey & _
					'		}' & _
					'	]' & _
					'}'
		
                ; I don't have a glue how the JSON should look like for the 'pointerMove' (to be honest)
		Case 'pointerMove'
			$sJSON = _
					'{' & _
					'	"dummy text one":"pointerMove"' & _
					'	,"dummy text two":' & $iValue & _
					'	,"dummy text three":' & $sPointerMoveVarOne & _
					'	,"dummy text four":' & $sPointerMoveVarTwo & _
					'}'
	EndSwitch

	Return $sJSON
EndFunc

Func _WD_JsonActionMouse($iValue, $sType = "")
    _WD_JsonAction('mouse', $iValue, "")
EndFunc

Func _WD_JsonActionPause($iValue)
    _WD_JsonAction('pause', $iValue)
EndFunc

Func _WD_JsonActionKey($iValue, $sType = "", $sKey = "")
    _WD_JsonAction('key', $iValue, $sType, $sKey)
EndFunc

Func _WD_JsonActionPointerMove($iValue, $sType = "", $sKey = "", $sPointerMoveVarOne = "", $sPointerMoveVarTwo = "")
    _WD_JsonAction('pointerMove', $iValue, "", "", $sPointerMoveVarOne, $sPointerMoveVarTwo)
EndFunc
```

The parameter handling in this example could be a miss match, caused by me, because it's hard for me out of the context which parameter is really optional and which not.

The first variant with separate functions would basically look like this:

``` autoit
Func _WD_JsonActionMouse($iValue, $sType = "")
	Return _
		'{' & _
		'	"button":' & $iValue & _
		'	,"type":"' & $sType & '"' & _
		'}'
EndFunc

Func _WD_JsonActionPause($iValue)
	Return _
		'{' & _
		'	"type":"pause"' & _
		'	,"duration":' & $iValue & _
		'}'
EndFunc

Func _WD_JsonActionKey($iValue, $sType = "", $sKey = "")
	Return _
		'{' & _
		'	"type":"key"' & _
		'	,"id":"keyboard_' & $iValue & '"' & _
		'	,"actions":[' & _
		'		{' & _
		'			"type":"' & $sType & '"' & _
		'			,"value":"' & $sKey & _
		'		}' & _
		'	]' & _
		'}'
EndFunc

Func _WD_JsonActionPointerMove($iValue, $sPointerMoveVarOne, $sPointerMoveVarTwo)
	Return _
        '{' & _
        '	"dummy text one":"pointerMove"' & _
        '	,"dummy text two":' & $iValue & _
        '	,"dummy text three":' & $sPointerMoveVarOne & _
        '	,"dummy text four":' & $sPointerMoveVarTwo & _
        '}'
EndFunc
```

The big advantage out of my perspective is that you would only pass the necessary parameter into the function 😀 .

**Comment by Danp2** [comment]
> The first variant with separate functions would basically look like this:
> 
> ```autoit
> Func _WD_JsonActionMouse($iValue, $sType = "")
> 	Return _
> 		'{' & _
> 		'	"button":' & $iValue & _
> 		'	,"type":"' & $sType & '"' & _
> 		'}'
> EndFunc
> ```

The parameters wouldn't be optional in this scenario, so your function declarations are off a bit. 😄 

> ```autoit
> Func _WD_JsonActionKey($iValue, $sType = "", $sKey = "")
>    _WD_JsonAction('key', $iValue, $sType, $sKey)
> EndFunc
> ```

Same thing with the wrapper functions. Also, the wrapper could look completely different than your example --

```autoit
Func WD_JsonActionKey($sAction, $sKey, $iKeyboard = 1)
    Return _WD_JsonAction('key', $iKeyboard, $sAction, $sKey)
EndFunc
```
The wrapper would be responsible for passing the correct parameters in the proper order to _WD_JsonAction. _WD_JsonActionPointerMove could have a completely different set of parameters .--
```autoit 
Func _WD_JsonActionPointerMove($sElement, $iXOffset = 0, $iYOffset = 0, $iDuration = 100)
    Return _WD_JsonAction('pointerMove',....)
EndFunc
```

Make sense?

**Comment by Sven-Seyfert** [comment]
Yes, you're right. The most of it make sense to me 😁 .

> The wrapper would be responsible for passing the correct parameters in the proper order to _WD_JsonAction. 

I still don't get it fully: So the _WD_JsonAction function would possibly have 5 or 6 or even ... 12 parameter in the future? How would you set a proper order of parameters individually to avoid empty string (default) arguments?

Sorry, it's late, right now 00:32 o'clock in germany. I have to rest and rethink it 😅 .

**Comment by mlipok** [comment]
@Danp2  would you develop the code ?
If so I will join in to review PR.

**Comment by Danp2** [comment]
Yes, I will code it once I've settled on the correct implementation.

**Comment by Danp2** [comment]
I've decided to split _WD_JsonAction into separate functions, which should be simpler to maintain in the future.

**Comment by Danp2** [comment]
FYI, this is ready for review in #167.

**Comment by Danp2** [comment]
And I've now recoded these routines to use Json_Put. Please take a look when you have a few minutes.
