### ISSUE TITLE
Question about Webdriver.chm

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#170]
Why "Introduction" in Webdriver.chm does not fully reflect the content of README.md ?
Is this created manually a not converted autlatically ?

To be more specific could you consider to add this following part of README.md to "Introduction" in Webdriver.chm 

```
Additional Resources
Webdriver Wiki
Discussion Threads on Autoit Forums
WebDriver UDF Help & Support part 1
WebDriver UDF Help & Support part 2
WebDriver UDF Help & Support part 3
```

Also another question: Why in Webdriver.chm there is lack of _WD_Capabilites* ?

**Comment by Sven-Seyfert** [comment]
Hi @mlipok ,

maybe we should search for a proper way to provide a "single source of truth" regarding the documentation.
To be honest: I feel bad about the current situation that there is a Wiki on autoitscripting.com, a README.md an so many additional forum posts about how and why.

- Why not using the possibilities of GitHub: README.md and Wiki on GitHub.
- The ensure the community in the forum is up to date, only reference links would be necessary.
- Also the *.chm which isn't often be created (as far as I know from @water) should use the "single source of truth" here on GitHub to provide the exact same information.

It's all about opinions, for sure, but I would do so and many companies already doing this.

Best regards
Sven

**Comment by Danp2** [comment]
@mlipok The "introduction" is currently a static HTML file that is maintained separately from README.md. I don't believe that those items belong in the introduction. I can probably create an entry for them following the Function Reference section.

@Sven-Seyfert Agree that we don't want or need to be maintaining the same information in multiple locations. I originally planned to use the wiki here, but chose not to proceed when @water published the version on the AI wiki.

P.S. I'm building the help file each time there's a new release. Pay attention to the version # on the Intro page and you'll note that it tracks along with the UDF version. 😉

**Comment by mlipok** [comment]
Thanks for answer.
What about _WD_Capabilites* in Webdriver.chm ?

**Comment by Danp2** [comment]
>  What about _WD_Capabilites* in Webdriver.chm ?

It will eventually be included. Currently, I haven't spent much time reviewing that code, function headers, etc. That needs to occur so that we are releasing accurate information.

**Comment by mlipok** [comment]
> I haven't spent much time reviewing that code, function headers, etc.

Do not do that till we close:
https://github.com/Danp2/WebDriver/issues/103
https://github.com/Danp2/WebDriver/issues/105
