### ISSUE TITLE
Changelog structure change to achieve some improvements

### ISSUE THREAD

**Issue by Sven-Seyfert** [Danp2/WebDriver#171]
Hi @Danp2 , hi @mlipok , hi to the other contributors 😀 ,

I already [announced](https://www.autoitscript.com/forum/topic/191990-webdriver-udf-w3c-compliant-version-01312022/?do=findComment&comment=1496005) that I want to create an Issue (later on a Pull Request) for the CHANGELOG.md structure.

**Now here we are 😅 :**
> A changelog should make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project. 
https://keepachangelog.com

Please have a look on that page to get an idea why I want to change the structure. It didn't make much sense to say it on my own - the page describe it even better than I could.

- I am already happy to see that it's not a REVISION.MD file anymore => 👍 @Danp2.
- As a showcase how it would look like, see my [forked](https://github.com/Sven-Seyfert/WebDriver/blob/master/CHANGELOG.md) project.
- One nice advantage is the comparison between the releases (or the tags of the releases). Just click on a version and you will get the commits and all the file changes which make it very handy to get a deeper view about the actually changes 😀 .

**What did I change so far:**
- As you can see there is the version number and the date which matches the date of the release.
- I changed it to categories (Added, Changed, Fixed etc.) which make the file more readable in my opinion.
  - That part was a bit tricky with RegEx, but it works and a good diff was also very helpful 😅 .
- I added the missing release [0.1.0.18.1] - 2019-04-30.

---

💡 **What is open and will be hopefully discussed:**
- The change to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) which is really common since few years and pretty easy to understand.
  - My suggestion is to start the next release with `1.0.0` or with `5.2.0` (based on the current version 0.5.1.1) when we want to stick with the other schema without the leading 0.

---

**Legend - Types of changes:**
- `Added` for new features.
- `Changed` for changes in existing functionality.
- `Deprecated` for soon-to-be removed features.
- `Removed` for now removed features.
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

---

### What do you think about this all 🤞 ?

Best regards
Sven

    Stay innovative!

**Comment by Danp2** [comment]
> Please have a look on that page to get an idea why I want to change the structure. It didn't make much sense to say it on my own - the page describe it even better than I could.

I actually ran across that site earlier today.

> What did I change so far

It looks nice at first glance. I'll take a closer look later.

> I added the missing release [0.1.0.18.1] - 2019-04-30

Man... you guys are tough! 😮  Not required IMO, but whatever. 

> My suggestion is to start the next release with 1.0.0 or with 5.2.0 (based on the current version 0.5.1.1) when we want to stick with the other schema without the leading 0.

Up til now I've always viewed this UDF as being in beta, so the 0.x version made sense to me. Now that it's been "polished" and has a help file, maybe it's time for the jump to 1.0. 🤔 

>  Semantic Versioning 

Let's definitely discuss this further. I'm confused by their summary section because their description of the major, minor, & patch labels doesn't seem to apply IMO.

**Comment by mlipok** [comment]
> Now that it's been "polished" and has a help file, maybe it's time for the jump to 1.0.

It may sound bad, but ... lets wait few next months.
I hope we will review some other functions which I mention in other Issues.
At least I must end my wd_capabilites.au3 refactoring.

**Comment by Sven-Seyfert** [comment]
@mlipok
> I hope we will review some other functions which I mention in other Issues.
At least I must end my wd_capabilites.au3 refactoring.

I'm not sure if that should really be a reason not to upgrade the version.
I will think about it and sort my argues, be prepared 😅 .

@Danp2 
I'm happy to read that there is no general disagreement or rejection. Of course we can and should discuss details, but I look to a positive future.

**Comment by mlipok** [comment]
> I will think about it and sort my argues, be prepared 😅 .

So this time I'll let it go ;)

**Comment by Danp2** [comment]
@Sven-Seyfert Will you be submitting a PR on this?

**Comment by Sven-Seyfert** [comment]
> Will you be submitting a PR on this?

Of course I can. But as far as I understood we want to wait a bit, at least until @mlipok finished his work on wd_capabilites.au3?
After that I planned to create the PR or should I do it now @Danp2 ?

**Comment by Danp2** [comment]
There isn't any reason to hold off on switching the changelog formatting, so feel free to submit PR now.
