### ISSUE TITLE
Logic of reordering code?

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#185]
@mlipok Please explain why having these listed in alphabetical order is important. I can understand with the error messages. How does changing the order within a Switch structure improve the code? Couldn't this actually make the code run slowing in some cases where commonly called commands are moved down in the comparison list?

_Originally posted  in https://github.com/Danp2/WebDriver/pull/183#pullrequestreview-875003426_

**Comment by mlipok** [comment]
I was not aware, I was not checking performance issues.
I focused on organizing the code in a way that facilitates its analysis and management.

Quick test:

```autoit
#include "..\wd_core.au3"
#include "z:\!!!_SVN_AU3\UDF_Forum\mLipok\ErrorLog.au3"

_Log_SetOutputFunction(ConsoleWrite)

_Example()

Func _Example()
	_Log_Durations(@ScriptLineNumber & ' START' )

	_WD_Window('', 'FAKE PRE TEST')
	_Log_Durations(@ScriptLineNumber & ' after FAKE PRE TEST' )
	ConsoleWrite(@CRLF)

	_WD_Window('', 'close')
	_Log_Durations(@ScriptLineNumber & ' after CLOSE 1' )
	ConsoleWrite(@CRLF)

	_WD_Window('', 'close')
	_Log_Durations(@ScriptLineNumber & ' after CLOSE 2' )
	ConsoleWrite(@CRLF)

	_WD_Window('', 'window')
	_Log_Durations(@ScriptLineNumber & ' after WINDOW' )
	ConsoleWrite(@CRLF)

	_WD_Window('', 'close')
	_Log_Durations(@ScriptLineNumber & ' after CLOSE 4' )
	ConsoleWrite(@CRLF)

EndFunc   ;==>_Example
```

Here are my logs

! [ 3 / 0 ] : 09-11-13.050 : Durations = 0.0002435 sec : from: { 9 START } to: { 12 after FAKE PRE TEST }
! [ 10 / 0 ] : 09-11-15.106 : Durations = 2.05515 sec : from: { 12 after FAKE PRE TEST } to: { 16 after CLOSE 1 }
! [ 10 / 0 ] : 09-11-17.131 : Durations = 2.0249518 sec : from: { 16 after CLOSE 1 } to: { 20 after CLOSE 2 }
! [ 6 / 0 ] : 09-11-19.184 : Durations = 2.0530938 sec : from: { 20 after CLOSE 2 } to: { 24 after WINDOW }
! [ 10 / 0 ] : 09-11-21.226 : Durations = 2.0414093 sec : from: { 24 after WINDOW } to: { 28 after CLOSE 4 }


btw.
will do some more test.

**Comment by mlipok** [comment]
Testing how fast `Case 'close'` is reached
`--> 09-16-13.504 : Durations = 0.0001123 sec : from: { 516 Func _WD_Window: before "Switch" } to: { 519 Func _WD_Window: just after: "Case close" }`

Testing how fast `Case 'window'` is reached
`--> 09-16-11.446 : Durations = 0.0001736 sec : from: { 516 Func _WD_Window: before "Switch" } to: { 566 Func _WD_Window: just after: "Case window" }`

The diferences is about 0.0001736 - 0.0001123 = 0.0000613 sec == 0,0613 msec

btw.
my CPU is:   i7-3770S

**Comment by Danp2** [comment]
Thanks for sharing your test results. Thankfully the difference is negligible,

**Comment by mlipok** [comment]
I nominate this ISSUE for closure ;)
