### ISSUE TITLE
_WD_FindElement + $bMultiple  : testing needed

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#189]
> But I think that a warrning about the fact that function will return collection of elements is required.

I'm not sure that is accurate. Have you tested to see if `_WD_FindElement` returns a collection when $bMultiple parameter isn't True?

_Originally posted by @Danp2 in https://github.com/Danp2/WebDriver/issues/174#issuecomment-1034875724_

btw.
Please assign this to me.

**TESTING procedure:**
$_WD_LOCATOR_ByTagName + tag name "button" + $bMultiple = false/true .
Testing should be performed on a page in 2 cases:

1. which contains: multiple "button"
2. which contains: single "button"

**Comment by Sven-Seyfert** [comment]
> For me is the behavior like expected, but maybe I miss something. Please have a look at these test results.

**Scenario 1**
Page with one button and $bMultiple is false

**Tested with**
- Browser: Chrome
- Headless: No
- Demo: DemoElements
- Url: https://demoqa.com/broken and https://demoqa.com/buttons
- $bMultiple = False
- Locator: $_WD_LOCATOR_ByTagName
- Tag: "button"

``` autoit
_WD_Navigate($sSession, "https://demoqa.com/broken")

$aElements = _WD_FindElement($sSession, $_WD_LOCATOR_ByTagName, "button", Default, False)
_ArrayDisplay($aElements, "Found Elements")
MsgBox('','',$aElements)
```

**Result**
Only the MsgBox appears with the element UUID, like expected = ✔

---

**Scenario 2**
Page with one button and $bMultiple is true

``` autoit
_WD_Navigate($sSession, "https://demoqa.com/broken")

$aElements = _WD_FindElement($sSession, $_WD_LOCATOR_ByTagName, "button", Default, True)
_ArrayDisplay($aElements, "Found Elements")
MsgBox('','',$aElements)
```

**Result**
_ArrayDisplay appears with the element UUID, like expected = ✔
MsgBox is empty = ✔

---

**Scenario 3**
Page with multiple buttons and $bMultiple is false

``` autoit
_WD_Navigate($sSession, "https://demoqa.com/buttons")

$aElements = _WD_FindElement($sSession, $_WD_LOCATOR_ByTagName, "button", Default, False)
_ArrayDisplay($aElements, "Found Elements")
MsgBox('','',$aElements)
```

**Result**
Only the MsgBox appears with the first found element (button) UUID, like expected = ✔

---

**Scenario 4**
Page with multiple buttons and $bMultiple is true

``` autoit
_WD_Navigate($sSession, "https://demoqa.com/buttons")

$aElements = _WD_FindElement($sSession, $_WD_LOCATOR_ByTagName, "button", Default, True)
_ArrayDisplay($aElements, "Found Elements")
MsgBox('','',$aElements)
```

**Result**
_ArrayDisplay appears with the elements (4x button) UUID, like expected = ✔
MsgBox is empty = ✔

**Comment by mlipok** [comment]
Thanks @Sven-Seyfert 
@Danp2 when you find this is all in this ISSUE please close it.
