### ISSUE TITLE
_WD_FrameEnter fails with Chrome web driver 

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#21]
Originally reported here -- https://www.autoitscript.com/forum/topic/191990-webdriver-udf-w3c-compliant-version-07112018/?do=findComment&comment=1397460

**Comment by ashishksaklani** [comment]
thanks Danp2 for your great efforts
myself i was trying to use it for last 1 week and its not working i found this after searching it on google 
that its a known issue 
glad you are working on it 

thanks again

**Comment by Danp2** [comment]
Fixed in Chromedriver 2.43
