### ISSUE TITLE
[Regression] __WD_CloseDriver

### ISSUE THREAD

**Issue by vkvtema** [Danp2/WebDriver#33]
__WD_CloseDriver doesn't work after rewrite if chromedriver path not default. Example:
`_WD_Option("Driver", "ChromeDriver\chromedriver.exe")`
After the script exit. Checking the task manager
![image](https://user-images.githubusercontent.com/59403221/72204114-7d8e6480-3485-11ea-8fda-208d30edb797.png)
I looked under the hood of the closing function to find out what the problem is, it seems that the new code does not return the process id if it is not the default path. Example:
![image](https://user-images.githubusercontent.com/59403221/72204276-15d91900-3487-11ea-98ed-8a508f783b63.png)

**Comment by Danp2** [comment]
Thanks for the report. I just pushed a commit that should fix this. Please test and report back.

**Comment by vkvtema** [comment]
> Thanks for the report. I just pushed a commit that should fix this. Please test and report back.

Thanks. Now it works)
