### ISSUE TITLE
_WD_SetElementValue + FF window is covered

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#334]
> I will be able to login to the restricted website to test this
> [$_WD_OPTION_Advanced TheDcoder fix](https://github.com/Danp2/au3WebDriver/pull/333/commits/6603e62641d0024c5a84d012c9217e4259beb8da)
> in next few days.

Already tested.
Works but not so good as I was expecting.

My issue may be related to FF version, driver version, windows version, any other ENV setting.

Here is what I'm having a problem (more or less accurate description).

When FF window is visible (aka TOPMOST) then all is fine.
When FF window is covered by another window, then value is set (visually you can notice that it was set) but when program click "SUBMIT" button then it turns out that the value has not been set correctly.

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/333#issuecomment-1173442432_

**Comment by mlipok** [comment]
I'm in process of preparing video from this issue.
I will send them to @TheDcoder  and @Danp2  via PM on the Au3Fourm

**Comment by Danp2** [comment]
It would be great if you could find a different website that is accessible by all. You will likely need this if you need to report to Mozilla.

**Comment by mlipok** [comment]
> It would be great if you could find a different website that is accessible by all. You will likely need this if you need to report to Mozilla.

I know, but it would be a stroke of luck to find such a case.

**Comment by Danp2** [comment]
Have you tried analyzing the site with https://builtwith.com/? That may help with understanding the framework / libraries involved, which could lead to finding another site with similar behavior.

**Comment by mlipok** [comment]
I was strugling with this all the day and I think I have found solution to my problems.
But as my client end work for today I must wait till tomorow to end my testing.

Curently I think the recent PR [_WD_SetElementValue $_WD_OPTION_Advanced usage](https://github.com/Danp2/au3WebDriver/pull/333)
did this trick because it was related to:
![image](https://user-images.githubusercontent.com/11089482/177161252-0a03038b-e8f1-4f19-bee2-74a11a2ee4ec.png)


All other issues may be related to my own code issues, but as I said I must wait till tomorrow to finish fixing/refactoring of my own code.

**Comment by Danp2** [comment]
@mlipok Ok to close this?

**Comment by mlipok** [comment]
Because of: I must finally finish one of my project related to this issue
.....
In this weekend I will do deeper research to check and confirm if all is fine.

**Comment by mlipok** [comment]
Works well.
This issue colud be closed.
