### ISSUE TITLE
_WD_ConsoleVisible(True) Hides Console

### ISSUE THREAD

**Issue by seadoggie01** [Danp2/WebDriver#34]
This is a little un-intuitive... when I pass True to _WD_ConsoleVisible, I would expect that the console would be visible, not hidden.

**Comment by Danp2** [comment]
Have you tested this? I see where the header may incorrectly describe the behavior of the parameter, but I think the console would be shown if you pass True to the function.

**Comment by seadoggie01** [comment]
Yes, it works contrary to the documentation, sorry. I also didn't realized that it needed to be after _WD_CreateSession :)

**Comment by Danp2** [comment]
Thanks for checking. I'll correct the header info.
