### ISSUE TITLE
Unused Variables/Strict Au3Check Settings

### ISSUE THREAD

**Issue by seadoggie01** [Danp2/WebDriver#35]
The variable $sErr is unused in the latest release (v0.3.0.1) in _WD_Window, _WD_FindElement, and _WD_ElementAction. When running with the strictest Au3Check parameters -d -w 1 -w 2 -w 3 -w 4 -w 5 -w 6 -w 7 -v3, a warning is generated

**Comment by Danp2** [comment]
Thanks @seadoggie01 for the feedback!
