### ISSUE TITLE
_WD_CreateSession 

### ISSUE THREAD

**Issue by tarreislam** [Danp2/WebDriver#37]
Hi,

Chrome 83.

The SessionId is not stored in `[Value]` anymore

https://github.com/Danp2/WebDriver/blob/2f4d8cce692ac66b6c16a345c5466204a9a6deaf/wd_core.au3#L431

**Comment by vkvtema** [comment]
Hmm, everything works for me.
"browserVersion":"83.0.4103.106"
"chromedriverVersion":"83.0.4103.39"
"sessionId":"5ccbbd39692e2f0cd174ffdc6b565b6b"

**Comment by Danp2** [comment]
@tarreislam I saw this same thing a few weeks back. I believe the issue was related to a bad Chrome release. Have you check to see if you are using the latest version of Chrome?

P.S. If that isn't the issue, then you will need to provide more details on your environment.

**Comment by Danp2** [comment]
Closed due to inactivity. Feel free to reopen as needed.
