### ISSUE TITLE
_WD_IsLatestRelease fails under some operating systems

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#40]
[Windows Server 2016](https://www.autoitscript.com/forum/topic/203475-chrome-automation-with-autoit/?do=findComment&comment=1461007)
[Windows 7](https://www.autoitscript.com/forum/topic/201106-webdriver-udf-help-support-ii/?do=findComment&comment=1460398)

**Comment by Danp2** [comment]
Confirmed behavior under a Windows Server 2016 VM. Also confirmed that _WinHttpSimpleSendSSLRequest.au3 from WinHTTP UDF examples also fails under Windows Server 2016. Seems to be related to accessing Github website. 

@dragana-r Would appreciate your input on this.

**Comment by Danp2** [comment]
Following call to WinHttpSendRequest, _WinAPI_GetLastError returns ERROR_WINHTTP_SECURE_FAILURE (12175)

**Comment by Danp2** [comment]
Code works as expected if I removed this commit -- https://github.com/dragana-r/autoit-winhttp/commit/6f4e4078f8083cd48fc1b114d3c40ff166a9a15d

**Comment by Danp2** [comment]
Replace `$WINHTTP_FLAG_SECURE_PROTOCOL_ALL` with `$WINHTTP_FLAG_SECURE_PROTOCOL_SSL3` (effectively removing `$WINHTTP_FLAG_SECURE_PROTOCOL_SSL2`) and it now works as expected under Windows Server 2016

**Comment by Danp2** [comment]
Confirmed that removing $WINHTTP_FLAG_SECURE_PROTOCOL_ALL also solves the issue with Win7.

**Comment by dragana-r** [comment]
Danp2 do you think there's a way to check for this specific error and resend the request after changing security protocol flags only in case of failure?
Could just removing SSL2 (and TLS1.0) broke other scripts?

**Comment by Danp2** [comment]
@dragana-r I imagine that's possible, but not the solution I would recommend. Seems like a simpler solution would be to add an optional parameter that allows the override of the default security protocol flags. This would also prevent breakage of existing scripts.

**Comment by AbdElRahmanV** [comment]
i have same issue with win7 but cant` solve it
