### ISSUE TITLE
launching WD with Chrome extension

### ISSUE THREAD

**Issue by nosovk** [Danp2/WebDriver#41]
According to documentation ChromeDriver allows to load extencions in headless mode.
https://sites.google.com/a/chromium.org/chromedriver/extensions
```
ChromeOptions options = new ChromeOptions();
options.addArguments("load-extension=/path/to/extension");
ChromeDriver driver = new ChromeDriver(options);
```

How can I accomplish same result with AutoIT?

```
_WD_Option('Driver', 'chromedriver.exe')
_WD_Option('Port', 9515)
_WD_Option('DriverParams', '--log-path="' & @ScriptDir & '\chrome.log"')
$sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"w3c": true, "args":[ "--profile-directory=Default","load-extension=\extencsion"]}}}}'
```
snippet was my starting point, also _WD_Options was one of varaints, but no result.
What is correct method to tell chromedriver that I need to load an extencion?

**Comment by nosovk** [comment]
Issue solved.
`load-extension=/extencsion` works like a charm
Problem in path delimeter. Windows uses \.
But chromedriver expects linux delimeter - /
If you will pass windows style delimeter chromedriver will fail with common error - wrong argument. But if you use linux path delimeter - everething works.

**Comment by Danp2** [comment]
Did you try escaping the backslash, so that your code looks like this?

`$sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"w3c": true, "args":[ "--profile-directory=Default","load-extension=c:\\path\\to\\extension"]}}}}'`
