### ISSUE TITLE
_WD_Attach() - $_WD_ERROR_Success - question

### ISSUE THREAD

**Issue by mlipok** [Danp2/WebDriver#55]
As I said in title, in function: **_WD_Attach()**    the returned @error **$_WD_ERROR_Success**   will never happen because the Else part will be used.

![image](https://user-images.githubusercontent.com/11089482/113702985-8565a480-96da-11eb-9872-38e6e7e46448.png)

**Comment by mlipok** [comment]
ah... this is very tricky... I found what you mean, Will do some refactoring and post some proposals.

**Comment by mlipok** [comment]
https://github.com/Danp2/WebDriver/pull/56

**Comment by Danp2** [comment]
@mlipok Seems you are talking to yourself now. :-P

Not sure that I see the issue here. When the main IF runs to successful completion, the code should run to the end of the function and return $_WD_ERROR_Success.

Have you tested this to be sure it doesn't work as expected?

**Comment by mlipok** [comment]
@Danp2 just take a look at #56

**Comment by Danp2** [comment]
I've looked at it. I can see where moving the parameter checking to the beginning would be more efficient. However, I wouldn't expect someone to continually pass an invalid value, so the "improvement" isn't earth shattering. Also, this doesn't match the coding style of the rest of the UDF unless you intend to refactor every function.

P.S. You still didn't answer my question. Does the existing function not work as intended?

**Comment by mlipok** [comment]
> Have you tested this to be sure it doesn't work as expected?

> P.S. You still didn't answer my question. Does the existing function not work as intended?

Works, properly as I notice here:

> ah... this is very tricky... I found what you mean

**Comment by mlipok** [comment]
> I can see where moving the parameter checking to the beginning would be more efficient.
In my proposal 
`If Not StringRegExp($sMode, '(?i)(title|url|html)', $STR_REGEXPMATCH) Then` 
Is used once, 
as so far, in case when user post inproper value to $sMode then all the code to `Case Else` was performed many times.

> Also, this doesn't match the coding style of the rest of the UDF 
What you mean ?

I see the same coding style in:
`_WD_GetFrameCount()` and others...

I mean in case when error lead directly to Return 

I prefer to use:
`If @error <> $_WD_ERROR_Success`
instead 
`If @error = $_WD_ERROR_Success`

> unless you intend to refactor every function.
As to refactoring other function ... work is in progress ...

**Comment by Danp2** [comment]
>  as so far, in case when user post inproper value to $sMode then all the code to Case Else was performed many times.

I believe it would only runs once, same as yours. ;-)

> What you mean ?
>
> I see the same coding style in:
> _WD_GetFrameCount() and others...

I mean that my coding style has been to check the value of things like $sMode as part of a Switch statement. 

> I mean in case when @error lead directly to Return I prefer to use:

Again... neither method is right or wrong. So, our coding styles are different.

> As to refactoring other function ... work is in progress :)

Appreciate your input. However, I hope that you can appreciate that this takes time / effort to review and approve your changes. Therefore, I would request that you focus on fixing or adding functionality rather than recoding because you don't like my coding style. :-)

**Comment by Danp2** [comment]
P.S. Can you fix the issue "title", which isn't accurate as discussed above?
