### ISSUE TITLE
_WD_UpdateDriver: COM Errors

### ISSUE THREAD

**Issue by seadoggie01** [Danp2/WebDriver#70]
While I will admit some fault here, _WD_UpdateDriver doesn't handle any COM errors resulting from unzipping the downloaded driver. For example, try unzipping to a non-existent directory.

I see a couple ways to fix this:
- include a COM error handler
- check to see if the $sInstallDirectory exists and create it if not
- Possibly: separate the lines with 2+ object level calls as this causes a fatal error (I think?) and check @error between

Happy to submit a pull request if you'd like, just let me know your preference :)

**Comment by seadoggie01** [comment]
It seems like the easiest way that I've found to correct this is to add this on line 1258 of wd_helper.au3 (can I link a specific in a file?)

`If Not FileExists($sInstallDir) Then DirCreate($sInstallDir)`

**Comment by Danp2** [comment]
I like this idea. However, I think more error checking will be needed. For example, what happens if your DirCreate fails?

**Comment by seadoggie01** [comment]
True... there's also no error checking after creating and using most of the objects in the function either. Most of the time I realize it will work, but ObjCreate highly suggests checking the @error value after.

**Comment by Danp2** [comment]
I'm cool with the direction you're headed. Submit a PR with the enhancements and then I'll review it.

**Comment by Danp2** [comment]
Did you make any headway on this, @seadoggie01?

**Comment by seadoggie01** [comment]
Ooops, sorry about the triple reference... I tried using the latest release version before realizing that there were newer changes... twice :)

**Comment by Danp2** [comment]
No worries. Thanks for the PR. I'll check it out in a bit.

**Comment by Danp2** [comment]
Closed in #85
