### ISSUE TITLE
WD_Demo: Provide example on how to pass additional arguments to ChromeDriver

### ISSUE THREAD

**Issue by rajan123456** [Danp2/WebDriver#71]
There is a difference in how additional arguments are passed to the web driver based on the browser being used.
The wd_demo provides an example of how to pass **acceptInsecureCerts** to the Firefox driver.

A similar example should be made available for the chrome function as well.

I will raise a PR for this soon.

**Comment by Danp2** [comment]
I don't know for sure without seeing an example, but this almost sounds like ti would be better as a FAQ on the wiki.

**Comment by rajan123456** [comment]
I have raised a PR for this example enhancement.
https://github.com/Danp2/WebDriver/pull/72

**Comment by Danp2** [comment]
@rajan123456 I'm not inclined to merge this PR because it doesn't improve the functionality of the script. I would suggest either  a FAQ as mentioned above or create a new document (`capabilites.md` or something similar) where multiple DesiredCapabilities definitions could be shown along with detailed descriptions.

**Comment by rajan123456** [comment]
Hi @Danp2 - I am looking to add an example within the Demo script which demonstrates how to add additional parameters while invoking the chrome driver. For example, in the SetupGecko block below, we have options such as **acceptInsecureCerts**.
```
Func SetupGecko()	
    _WD_Option('Driver', 'geckodriver.exe')	
    _WD_Option('DriverParams', '--log trace')	
    _WD_Option('Port', 4444)
    $sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts":true}}}'
EndFunc   ;==>SetupGecko
```
For the chrome driver, the syntax is slightly different, and I do not want to disable certificate verification by default, hence added a simple option in the demo script, **start-maximized**. A user looking at the script would be able to easily extrapolate other arguments based on the chrome driver documentation.
```
Func SetupChrome()	
    _WD_Option('Driver', 'chromedriver.exe')	
    _WD_Option('Port', 9515)	
    _WD_Option('DriverParams', '--verbose --log-path="' &amp; @ScriptDir &amp; '\chrome.log"')
    $sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"w3c": true, "excludeSwitches": [ "enable-automation"], "args":["start-maximized"] }}}}'EndFunc   ;==>SetupChrome
```

> I would suggest either a FAQ as mentioned above or create a new document (capabilites.md or something similar) where multiple DesiredCapabilities definitions could be shown along with detailed descriptions.

Let me know if you have a similar FAQ or document for documenting other capabilities for browsers such as Firefox, Edge - and I would add the note to them as well.

**Comment by Danp2** [comment]
Hi @rajan123456 -- I gave you a couple of alternatives above. Personally, I like the idea of creating a new .md file where different Desired Capabilities configurations could be documented.
