### ISSUE TITLE
_WD_WaitElement: Return element instead of static value

### ISSUE THREAD

**Issue by TheDcoder** [Danp2/WebDriver#80]
`_WD_WaitElement` can replace the redundant `_WD_FindElement` call if it returns the element instead of `1` on success.

**Comment by Danp2** [comment]
@TheDcoder Not sure what you mean. Which redundant call to _WD_FindElement?

**Comment by TheDcoder** [comment]
I normally use the same selector for both FindElement and WaitElement, so in that case I have to call both of those functions with the same arguments.

**Comment by Danp2** [comment]
1) You should stay more up-to-date as that feature was added back in v0.3.1.0 
2) You make a good argument
3) Feel free to submit a PR with the suggested changes

**Comment by TheDcoder** [comment]
Yeah, I should update.

Sorry about the PR though, can't do it because I don't have git setup in my Windows VM and it's too much work for a simple feature. Don't worry about credit, if that is what you were thinking about :)

**Comment by Danp2** [comment]
No, not worried about the credit. Was just hoping for someone else to code the change. ;-)

**Comment by Danp2** [comment]
@TheDcoder Take a look at #81. I believe this still needs some revision related to $_WD_OPTION_NoMatch because you can't return an Element ID for a non-existent element.

**Comment by TheDcoder** [comment]
The changes look good, my suggestion would be to make it return whatever `FindElement` would in case there is no matching element... I can't even recall what it does because I don't usually check the return value on failure :rofl:
