### ISSUE TITLE
How to recover from "Browsing context has been discarded"?

### ISSUE THREAD

**Issue by Danp2** [Danp2/WebDriver#88]
Originally reported here ==> https://www.autoitscript.com/forum/topic/192730-webdriver-udf-help-support/?do=findComment&comment=1415354

Was thought to be fixed in https://github.com/Danp2/WebDriver/releases/tag/0.1.0.17

**Comment by Danp2** [comment]
Upon further review, I believe this issue would affect all UDF commands that attempt to communicate with the webdriver because the current browser context was lost when the user manually closed the active tab.

**Comment by seadoggie01** [comment]
Either I don't understand this correctly, or I'm not getting the error

	; Setup WebDriver, then do this:
	_WD_NewTab($sSession, False, Default, "https://www.google.com")

	MsgBox($MB_OK, $__g_sTitle, "Please close the active tab.")

	; This is expected to fail, currently pointing to destroyed tab
	_WD_Navigate($sSession, "https://www.google.com")

	; To recover, get an array of window handles and use one
	Local $aHandles = _WD_Window($sSession, "handles")
	_WD_Window($sSession, "switch", '{"handle":"' & $aHandles[0] & '"}')

	; Now this will work
	_WD_Navigate($sSession, "https://www.google.com")

**Comment by Danp2** [comment]
@seadoggie01 Have you tried it? I believe the _WD_Window commands will also fail.

**Comment by seadoggie01** [comment]
Yes, I tested that code before posting it, it works for me (Chrome v93.0.4577.63)

**Comment by Danp2** [comment]
Ok... I'll take another look. I was previously testing with Firefox, so I'll be sure to check Chrome as well.

**Comment by seadoggie01** [comment]
This works with Edge as well for me. I don't have Firefox to test with

**Comment by Danp2** [comment]
> ; Setup WebDriver, then do this:
>_WD_NewTab($sSession, False, Default, "https://www.google.com")

FYI, this doesn't actually switch the browser context to the new tab because of the 2nd parameter being False. Need to make it True or Default for a valid test.

**Comment by seadoggie01** [comment]
Oh, okay. It works both ways for me. I can close all tabs that the WebDriver may have known about, open a third tab, and it still continues

**Comment by Danp2** [comment]
Yes, it's working for me as well with simplified code. I think it was failing yesterday when using the code provided by the first link.

> WebDriver knows Tab1 (empty), Tab2 (Google), but not Tab3 (User created). After closing Tabs 1+2, getting a list of handles should return Tab3

Not sure that I follow. Are you saying that no tabs are returned in this instance?

**Comment by seadoggie01** [comment]
I thought that was a confusing explanation :)
I was saying that I could open a new tab (outside of code), close the tabs the webdriver opened, and it would continue happily. As in, webdriver doesn't have an internal reference to the tabs that are open, it only cares if it's the same session.

**Comment by Danp2** [comment]
I just pushed a small update to _WD_NewTab so that it correctly returns an error when the call to _WD_Window fails. That's the only issue I've been able to identify thus far. 

FWIW, I've considered writing another helper function that could be used to test the current browser context for validity.

**Comment by Danp2** [comment]
Closing this for now as it seems to be a non issue.
