### ISSUE TITLE
Possibility of webdriver's background work

### ISSUE THREAD

**Issue by nika90426** [Danp2/WebDriver#91]
Hi, Danp2!
First of all, I'd like to appreciate your effort for this nice library.

I'm now developing a simple automation tool by using chrome webdriver, and everything is almost ok.
But the chrome always take the focus to itself while processing action, so I feel uncomfortable when I want to do some other works while running the script.
I found that the built-in functions of IE has no problem like this.
So my question is,
Is possible to make the chrome work in background like _IE functions?

I look forward to your reply.
Thank you.

**Comment by Danp2** [comment]
Hi @nika90426,

Have you tried to determine which commands are causing the focus change? Does it also occur if you test with FIrefox or Edge?

Depending on your needs, you may be able to solve this by running the browser in "headless" mode. 

Dan

**Comment by nika90426** [comment]
I know "headless" mode is one of the solutions, but its not what I exactly want.
Let me explain what I want.

For example, suppose there exists two tabs in chrome browser.
And I want to do some actions on currently not focused tab.
So when I call _WD_Attach() function to find the not focused tab, chrome automatically take focus to itself and switch to the tab.
But when I use _IEAttach(), there is no such like this problem.
_IEAttach() can find the specific tab without any focusing action, and even _IENavigate() can navigate to url without focusing the tab.
I want to make chrome exactly work like _IEAttach() and _IENavigate().
I wonder if its possible by using this library.

I still haven't tested with Firefox or Edge, so I don't know what will happen on Firefox or Edge.

Nika

**Comment by Danp2** [comment]
_WD_Attach cycles through the available tabs until it finds a match. Are you calling this function regularly? If so, why?

**Comment by nika90426** [comment]
Yes, I'm calling _WD_Attach regularly.
The main html page spends long time for complete loading, so I created two tab (first - main page, second - other page) and made each tab to do their own work.
For this, I should have to use _WD_Attach regularly.
And chrome takes focus to itself and repeats switching between two tabs.

Finally,
1. I cannot do other works on my PC while running the script. (due to chrome's focusing)
2. I want chrome to always focus the main page's tab and to make other tab work in background, but it looks impossible now.

Can I solve these two problems?

**Comment by Danp2** [comment]
It would make more sense to do the following --

- Save the result from calling _WD_Attach
- Use _WD_Window and this "handle" to switch directly to the desired tab

You may want to rethink your design. Doesn't chromedriver support multiple active sessions? If so, you may be able to have a separate session established for each tab and then just use the appropriate SessionID for the desired target.

**Comment by Danp2** [comment]
@nika90426 Is this something that you still want kept open?
