### ISSUE TITLE
_WD_IsLatestRelease ==> General Error

### ISSUE THREAD

**Issue by AbdElRahmanV** [Danp2/WebDriver#96]
Hello all

Hope you all well 

i faced This issue 

https://ibb.co/60dHRJZ
(https://user-images.githubusercontent.com/94099046/141244890-4aa7aec7-6f8f-4772-967a-84d33c9dedac.png)

When i try use The compiled exe on windows 7 but it`s work on windows 10

and when run it (F5) as Script on windows 7 it`s work good .

i don't know the reason !

**Comment by AbdElRahmanV** [comment]
I just saw this same closed issue 
https://github.com/Danp2/WebDriver/issues/40
Will test this solution

**Comment by AbdElRahmanV** [comment]
still same issue

**Comment by Danp2** [comment]
I've replied to your post on the forum. I'll watch for your reply there.

**Comment by mlipok** [comment]
> I've replied to your post on the forum. I'll watch for your reply there.

Please add here link to forum.

**Comment by AbdElRahmanV** [comment]
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/page/21/#comments
